services:
  # Frontend - React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Backend - Node.js API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/data/reading_tracker.db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/app/data

  # Database initialization
  db-init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["node", "scripts/init-db.js"]
    depends_on:
      - backend
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: